config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'tops/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tops#index'
  get '/prefecture/:id', to: 'tops#pref_index', as: :pref_index
  get 'show/:id', to: 'tops#show', as: :show
  get '/search', to: 'search_parmacy#search_index', as: :search_pharmacy
  get '/login' , to: 'sessions#new', as: :sign_in
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  namespace :shop do
    get "/new", to: "top#new"
    get "/dashboard/:id", to: "top#dashboard", as: :dashboard
    post "/create", to: "top#create", as: :create
    get "/des/:id", to: "shop_contents#des", as: :des
    post "/des/create", to: "shop_contents#create", as: :des_create
    get "des/edit/:id", to: "shop_contents#edit", as: :des_edit
    post "des/update/:id", to: "shop_contents#update", as: :des_update
    get "new/avatar", to: "shop_contents#avatar", as: :avatar
    post "create/avatar", to: "shop_contents#avatar_process", as: :avatar_process
  end

  namespace :admin do
    root to: "top#index"
    get "sign_up", to: "top#new", as: :new
    post "create", to: "top#create"
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  before_save { self.email.downcase }
  mount_uploader :shop_img, ShopImgUploader
  belongs_to :prefecture
  belongs_to :city
  has_one :shop_desc
  has_many :products

  EMAIL_VALID_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,     presence: true, length: { maximum: 50 }, on: :create
  validates :name,     presence: true, on: :update, allow_blank: true
  validates :email,    presence: true, length: { maximum: 255 }, format: { with: EMAIL_VALID_REGEX }, uniqueness: { case_sensitive: false },on: :create
  validates :email,    presence: true, on: :update, allow_blank: true
  validates :password, presence: true, length: { minimum: 6 },on: :create
  validates :password, presence: true, on: :update, allow_blank: true
  has_secure_password
  
end

app/controllers/admin/tops_controller.rb
class Admin::TopsController < ApplicationController
end

app/controllers/shop/shop_contents_controller.rb
class Shop::ShopContentsController < ApplicationController
  def des
    @shop_contents = ShopContent.new
    @shop = Shop.find(params[:id])
  end

  def create
    @shop_content = ShopContent.new(des_params.merge(shop_id: current_shop.id))
    if @shop_content.save
      flash[:success] = "店舗説明作成しました"
      redirect_to show_path(current_shop)
    else
      flash[:danger] = "店舗説明が作成されませんでした"
      redirect_to shop_des_path(current_shop)
    end
  end

  def edit
    @shop_content = ShopContent.find(params[:id])

  end
    
  def update
    @shop_content = ShopContent.find(params[:id])
    if @shop_content.update(edit_params.merge(shop_id: current_shop.id))
      flash[:success] = "店舗説明編集しました"
      redirect_to show_path(current_shop)  
    else
      flash[:danger] = "店舗説明の編集が失敗しました"
      redirect_to shop_des_edit_path(@shop_content) 
    end
  
  end  

  def avatar
    @shop_avatar = ShopAvatar.new
  end

  def avatar_process
    avatar = params[:shop][:avatar]
    if avatar.present?
      @shop_avatar = ShopAvatar.new(avatar_params.merge(shop_id: current_shop.id))
        if @shop_avatar.save?
          flash[:success] = "写真を掲載しました"
          redirect_to show_path(current_shop)
        else
          flash[:danger] = "写真を掲載できませんでした"
          redirect_to shop_avatar_path
        end
    else
      redirect_to show_path(current_shop)
    end
  end
  private

  def des_params
    params.permit(:description)
  end

  def edit_params
    params.require(:shop_content).permit(:description)
  end

  def avatar_params
    params.require(:shop_avatar).permit(:avatar)
  end
end

app/controllers/shop/top_controller.rb
class Shop::TopController < ApplicationController
 
<<<<<<< HEAD
  before_action :authorize_shop, only: [:dashboard, :update, :desc, :descprocess]
  before_action :correct_shop, only: [:dashboard, :update, :desc]
    #new actionはadministrator権限にする
=======
  before_action :authorize_shop, only: [:edit, :update]
  before_action :correct_user, only: [:dashboard]
    
>>>>>>> 1dc7385d28732438a05c4f5d553bec4f306a5f4e
    def new
      @shop = Shop.new
    end
    
    def create
<<<<<<< HEAD
      
      shop_img = params[:shop][:shop_img]
      if shop_img.present?
          @shop = Shop.new(shop_params.merge(shop_img: shop_img))
          if @shop.save
            login(@shop)
            flash[:success] = "成功しました"
            redirect_to shop_dashboard_path(@shop)
          else
            flash[:danger] = "だめ"
            redirect_to shop_new_path
          end
          
      else
          @shop = Shop.new(shop_params)
          if @shop.save
            flash[:success] = "店舗ページ作成"
            redirect_to shop_dashboard_path(@shop)
          else
            flash[:danger] = "作成できませんでした"
            redirect_to shop_new_path
          end
          
      end
    end
    
    def dashboard
      @shop = Shop.find(params[:id])
    end
    
    def desc
      @shop_desc = ShopDesc.new
    end
    
    def descprocess
      @shop_desc = ShopDesc.new(desc_params.merge(shop_id: current_shop.id))
      if @shop_desc.save
        flash[:success] = "店舗概要を作成しました"
        redirect_to show_path(current_shop)
      else
        flash[:danger] = "店舗概要を作成できませんでした"
        redirect_to shop_desc_path
      end
    end
    
    def imgprocess
      shop = Shop.find_by(id: current_shop.id)
      shop_img = params[:shop][:shop_img]
     if shop.update(shop_img: shop_img)
       flash[:success] = "画像を変更しました"
       redirect_to shop_dashboard_path(current_shop)
     else
       flash[:danger] = "画像を変更できませんでした"
       redirect_to shop_dashboard_path(current_shop)
     end
    end
    
    def desc_edit
      @shop_desc = ShopDesc.find(params[:id])
    end
    
    def desc_edit_process
      @shop_desc = ShopDesc.find_by(shop_id: current_shop.id)
      if @shop_desc.update(desc_params.merge(shop_id: current_shop.id))
        
        flash[:success] = "変更しました"
        redirect_to shop_dashboard_path(current_shop)
      else
        flash[:danger] = "変更できませんでした"
        redirect_to desc_edit_path(current_shop)
       
      end
    end
    
    def product
      @product = Product.new
    end
    
    def product_process
     
      product_img = params[:product][:product_image]
      if product_img.blank?
         @product = Product.new(product_params.merge(shop_id: current_shop.id))
        if @product.save
          flash[:success] = "登録しました（写真はデフォルト）"
          redirect_to shop_dashboard_path(current_shop)
        else
          flash[:danger] = "登録できませんでした"
          render 'product'
        end
      else
        @product = Product.new(product_params.merge(shop_id: current_shop.id, product_image: product_img))
        if @product.save
          flash[:success] = "登録しました"
          redirect_to shop_dashboard_path(current_shop)
        else
          flash[:danger] = "登録できませんでした"
          render 'product'
        end
      end
    end
    
    def product_delete
      @product = Product.find(params[:id])
      if @product.destroy
        flash[:success] = "削除しました"
        redirect_to shop_dashboard_path(current_shop)
      else
        flash[:danger] = "削除できませんでした"
        render 'dashboard'
      end
=======
    if params[:shop][:shop_img].present?
        @shop = Shop.new(shop_params)
        if @shop.save
          login(@shop)
          flash[:success] = "登録しました"
          redirect_to show_path(@shop)
        else
          flash[:danger] = "登録できませんでした!!!"
          redirect_to shop_new_path
        end
    else
      @shop = Shop.new(no_shop_params)
      if @shop.save
        login(@shop)
        flash[:success] = "登録しました"
        redirect_to show_path(@shop)
      else
        flash.now[:danger] = "登録できませんでした"
        redirect_to shop_new_path
      end
    end
    
    end
    
    def dashboard
      @shop = Shop.find(params[:id])
      @shop_contents = ShopContent.new
>>>>>>> 1dc7385d28732438a05c4f5d553bec4f306a5f4e
    end
    
   
   
    private 
    
    def shop_params
<<<<<<< HEAD
      params.require(:shop).permit(:name, :email, :password, :password_confirmation, :prefecture_id, :city_id)
    end
    
    def desc_params
     params.require(:shop_desc).permit(:description, :shop_id)
    end
    
    def product_params
      params.require(:product).permit(:name, :description)
    end
=======
      params.require(:shop).permit(:name, :email, :password, :password_confirmation, :prefecture_id, :city_id, :shop_img)
    end
    
    def no_shop_params
      params.require(:shop).permit(:name, :email, :password, :password_confirmation, :prefecture_id, :city_id)
    end
    
>>>>>>> 1dc7385d28732438a05c4f5d553bec4f306a5f4e
    
    
   
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end

  def pref_index
    @prefecture = Prefecture.find(params[:id])
    
    if params[:name].present?
      @prefectures = Prefecture.where("name like ?", "%#{params[:name]}%")
    end
  end

  def show
    @shop = Shop.find(params[:id])
  end
end

app/helpers/admin/tops_helper.rb
module Admin::TopsHelper
end

app/helpers/shop/shop_contents_helper.rb
module Shop::ShopContentsHelper
end

app/helpers/shop/top_helper.rb
module Shop::TopHelper
    
    
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/shop/top/_desc_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_with(model: @shop_desc, url: shop_descprocess_path, method: :post, local: true) do |f| %>
        <div class="form-group">
          <%= f.label :descrption, '店舗概要' %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
          <%= f.submit '作成', class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shop/top/dashboard.html.erb
<<<<<<< HEAD
<% provide(:title, "#{current_shop.name}様ページ") %>
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>現在の設定情報</h1>
      <h3><%= current_shop.name %></h3>
      <p><%= "#{@current_shop.name}様のメインイメージ" %></p>
      <% if current_shop.shop_img.present? %>
        <%= image_tag(@current_shop.shop_img_url) %>
      <% else %>
        <img src="https://dummyimage.com/300x200/000000/fae6fa.jpg&text=%E3%81%93%E3%82%8C%E3%81%AF%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%81%A7%E3%81%99">
      <% end %>
        <%= form_with(model: @current_shop, url: shop_imgprocess_path(current_shop), method: :post, local: true ) do |f| %>
          <%= f.file_field :shop_img %>
          <%= f.submit '変更', class: 'btn btn-success btn-xs' %>
        <% end %>
        <div class="shop_description">
          
          <% if @shop.shop_desc.nil? %>
            <%= link_to "店舗概要設定", shop_desc_path(current_shop) %>
          <% else %>
          <p>現在の店舗概要</p>
            <%= @shop.shop_desc.description %>
            <%= link_to '編集', shop_descedit_path(@shop) %>
            <i class="fa fa-camera"></i>
          <% end %>
        </div>
        
        <div class="shop_product">
          <%= link_to "取り扱い商品登録", shop_product_path(current_shop) %>
          <p>現在の取り扱い商品一覧</p>
          <ul>
            <% current_shop.products.each do |product| %>
              <li>
                <%= product.name %>
              </li>
            <%= link_to '削除', shop_product_delete_path(product), method: :delete %>
            <% end %>
          </ul>
        </div>
          <% if logged_in_shop? %>
            <%= link_to 'ログアウト', logout_path, method: :delete, data: { confirm: '本当にログアウトしますか？' } %>
          <% end %>
    </div>
  </div>
</div>

=======
<div class="container" style="width: 80%;">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <%= link_to show_path(current_shop) do %>
          <%= @shop.name %> 
        <% end %>
          <div class="des_link">
            <% if @shop.shop_contents.nil? %>
              <%= link_to "店舗説明", shop_des_path(current_shop) %>
            <% else %>
              <% @shop.shop_contents.each do |content| %>
                <%= link_to "店舗説明編集", shop_des_edit_path(content) %>
              <% end %>
            <% end %>
          </div>
        <% if logged_in_shop? %>
        <%= link_to 'ログアウト', logout_path, method: :delete, data: { confirm: '本当にログアウトしますか？' } %>
    <% end %>
    </div>
  </div>
</div>
>>>>>>> 1dc7385d28732438a05c4f5d553bec4f306a5f4e

app/views/shop/top/desc.html.erb
<%= render partial: 'shop/top/desc_form' %>

app/views/shop/top/desc_edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_with(model: @shop_desc, url: shop_desceditprocess_path(current_shop), method: :post, local: true) do |f| %>
        <div class="form-group">
          <%= f.label :descrption, '店舗概要' %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
          <%= f.submit '作成', class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shop/top/new.html.erb
<div class="container" style="width: 80%;">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
<<<<<<< HEAD
      <%= form_with(model: @shop, url: shop_create_path, method: :post, local: true) do |f| %>
      
=======
      <%= form_with(model: @shop, url: shop_create_path, method: :post) do |f| %>
      <%render partial: 'layouts/error_messages' %>
>>>>>>> 1dc7385d28732438a05c4f5d553bec4f306a5f4e
        <div class="form-group">
          <%= f.label :name, '店舗名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, 'パスワード' %>
          <%= f.password_field :password, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, 'パスワード再入力'%>
          <%= f.password_field :password_confirmation, class: 'form-control'%>
        </div>
      <div class="form-group">
        <%= f.label :prefecture_id, '所属都道府県'%>
        <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, include_blank: '都道府県' %>
        <%= f.select :city_id, [], include_blank: '市町村を選択してください。' %>
        <% Prefecture.all.each do |pref| %>
        <template id="<%= "city_of_prefecture#{pref.id}" %>">
          <%= f.collection_select :city_id, pref.cities, :id, :name, include_blank: '市町村選択' %>
        </template>
        <% end %>
      </div>
      
        <%= f.label :shop_img, '店舗メイン画像' %>
        <%= f.file_field :shop_img %>
      
      <%= f.submit '店舗登録', class: 'btn btn-lg btn-primary' %>
      
      <% end %>
      <%= debug(params) %>
    <div>
  </div>
<<<<<<< HEAD
</div>
=======
</div>
>>>>>>> 1dc7385d28732438a05c4f5d553bec4f306a5f4e

app/views/shop/top/product.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @product, url: shop_product_create_path, method: :post, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, '商品名' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description, '商品説明' %>
        <%= f.text_area :description, class: 'form-control', rows: 5 %>
      </div>
      <%= f.file_field :product_image %>
      <%= f.submit '登録する', class: 'btn btn-primary btn-lg' %>
      <% end %>
    </div>
  </div>
</div>