config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'tops/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tops#index'
  get '/prefecture/:id', to: 'tops#pref_index', as: :pref_index
  get 'show/:id', to: 'tops#show', as: :show
  get '/search', to: 'search_parmacy#search_index', as: :search_pharmacy
  get '/login' , to: 'sessions#new', as: :sign_in
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  namespace :shop do
    get "/new", to: "top#new"
    get "/dashboard/:id", to: "top#dashboard", as: :dashboard
    post "/create", to: "top#create", as: :create
    get "/des/:id", to: "shop_contents#des", as: :des
    post "/des/create", to: "shop_contents#create", as: :des_create
    get "des/edit/:id", to: "shop_contents#edit", as: :des_edit
    post "des/update/:id", to: "shop_contents#update", as: :des_update
    get "new/avatar", to: "shop_contents#avatar", as: :avatar
    post "create/avatar", to: "shop_contents#avatar_process", as: :avatar_process
  end

  namespace :admin do
    root to: "top#index"
    get "sign_up", to: "top#new", as: :new
    post "create", to: "top#create"
  end
end

app/controllers/search_parmacy_controller.rb
class SearchParmacyController < ApplicationController
    def search_index
        
       if params[:commit].present?
         @prefectures = Prefecture.where("prefecture_id: ?", "params[:search][:id]")
         binding.remote_pry
       end
       
    end
end

app/helpers/search_parmacy_helper.rb
module SearchParmacyHelper
end

app/views/search_parmacy/_map.html.erb
  <img src="/map_image/japan_map-1-1.jpg" usemap="#ImageMap" alt="" class="map_image" />

  
<map name="ImageMap">
  <area shape="poly" coords="508,15,547,14,603,49,618,48,619,104,573,114,527,97,513,114,494,114,494,85,507,63,507,63" href="https://kimeido.info/prefecture/1" alt="北海道" />
  <area shape="poly" coords="492,136,503,137,512,141,528,142,536,126,546,125,545,151,494,152,494,152" href="https://kimeido.info/prefecture/2" alt="青森" />
  <area shape="poly" coords="523,158,547,157,545,192,522,190,522,190" href="https://kimeido.info/prefecture/3" alt="岩手県" />
  <area shape="rect" coords="493,156,519,191" href="https://kimeido.info/prefecture/5" alt="秋田県" />
  <area shape="rect" coords="521,195,548,223" href="https://kimeido.info/prefecture/4" alt="宮城県" />
  <area shape="rect" coords="494,196,516,223" href="https://kimeido.info/prefecture/6" alt="山形県" />
  <area shape="rect" coords="495,230,536,246" href="https://kimeido.info/prefecture/7" alt="福島県" />
  <area shape="rect" coords="497,254,514,278" href="https://kimeido.info/prefecture/9" alt="栃木県" />
  <area shape="rect" coords="469,254,487,277" href="https://kimeido.info/prefecture/10" alt="群馬県" />
  <area shape="rect" coords="465,284,517,296" href="https://kimeido.info/prefecture/11" alt="埼玉県" />
  <area shape="poly" coords="524,254,540,254,540,266,548,272,546,297,522,294,523,293" href="https://kimeido.info/prefecture/8" alt="茨城県" />
  <area shape="poly" coords="514,301,546,301,546,350,526,350,527,320,514,313,514,313" href="https://kimeido.info/prefecture/12" alt="千葉県" />
  <area shape="rect" coords="474,299,507,312" href="https://kimeido.info/prefecture/13" alt="東京都" />
  <area shape="rect" coords="474,319,512,336" href="https://kimeido.info/prefecture/14" alt="神奈川県" />
  <area shape="rect" coords="446,300,471,326" href="https://kimeido.info/prefecture/19" alt="山梨県" />
  <area shape="poly" coords="447,229,472,228,480,215,490,215,489,248,447,247,447,247" href="https://kimeido.info/prefecture/15" alt="新潟県" />
  <area shape="poly" coords="425,252,462,253,461,297,442,295,442,326,427,324,427,324" href="https://kimeido.info/prefecture/20" alt="長野県" />
  <area shape="rect" coords="405,229,444,247" href="https://kimeido.info/prefecture/16" alt="富山県" />
  <area shape="poly" coords="383,197,414,196,413,205,403,212,402,249,376,248,376,238,384,221,384,221" href="https://kimeido.info/prefecture/17" alt="石川県" />
  <area shape="poly" coords="406,253,406,253,424,254,423,326,378,326,379,286,406,284,406,284" href="https://kimeido.info/prefecture/21" alt="岐阜県" />
  <area shape="poly" coords="376,254,402,253,402,283,339,280,338,268,369,268,369,268" href="https://kimeido.info/prefecture/18" alt="福井県" />
  <area shape="rect" coords="351,286,371,317" href="https://kimeido.info/prefecture/25" alt="滋賀県" />
  <area shape="poly" coords="412,333,470,332,470,357,462,359,460,351,444,351,443,364,411,362,411,362" href="https://kimeido.info/prefecture/22" alt="静岡県" />
  <area shape="poly" coords="379,333,408,331,407,363,388,362,387,351,376,349,376,349" href="https://kimeido.info/prefecture/23" alt="愛知県" />
  <area shape="rect" coords="317,306,346,344" href="https://kimeido.info/prefecture/29" alt="奈良県" />
  <area shape="poly" coords="351,324,371,323,372,375,335,374,333,350,349,350,351,343" href="https://kimeido.info/prefecture/24" alt="三重県" />
  <area shape="poly" coords="299,268,330,268,333,285,345,284,345,300,298,300,298,300" href="https://kimeido.info/prefecture/26" alt="京都府" />
  <area shape="rect" coords="298,306,312,331" href="https://kimeido.info/prefecture/27" alt="大阪府" />
  <area shape="poly" coords="298,334,312,335,312,348,327,349,327,373,300,373,300,373" href="https://kimeido.info/prefecture/30" alt="和歌山県" />
  <area shape="rect" coords="270,270,294,316" href="https://kimeido.info/prefecture/28" alt="兵庫県" />
  <area shape="rect" coords="237,270,263,284" href="https://kimeido.info/prefecture/31" alt="鳥取県" />
  <area shape="rect" coords="236,291,266,317" href="https://kimeido.info/prefecture/33" alt="岡山県" />
  <area shape="rect" coords="192,267,231,284" href="https://kimeido.info/prefecture/32" alt="島根県" />
  <area shape="rect" coords="205,291,229,316" href="https://kimeido.info/prefecture/34" alt="広島県" />
  <area shape="poly" coords="163,266,187,267,188,288,198,289,198,318,171,317,172,292,164,291,164,291" href="https://kimeido.info/prefecture/35" alt="山口県" />
  <area shape="rect" coords="243,336,286,350" href="https://kimeido.info/prefecture/37" alt="香川県" />
  <area shape="rect" coords="242,354,285,370" href="https://kimeido.info/prefecture/36" alt="徳島県" />
  <area shape="poly" coords="181,348,189,337,206,336,215,350,238,353,238,371,182,369,182,369" href="https://kimeido.info/prefecture/38" alt="愛媛県" />
  <area shape="poly" coords="182,374,284,374,285,401,261,401,247,391,208,391,201,401,182,398,182,398" href="https://kimeido.info/prefecture/39" alt="高知県" />
  <area shape="rect" coords="119,297,154,321" href="https://kimeido.info/prefecture/40" alt="福岡県" />
  <area shape="rect" coords="128,323,152,358" href="https://kimeido.info/prefecture/44" alt="大分県" />
  <area shape="rect" coords="129,362,150,391" href="https://kimeido.info/prefecture/45" alt="宮崎県" />
  <area shape="rect" coords="99,324,124,390" href="https://kimeido.info/prefecture/43" alt="熊本県" />
  <area shape="poly" coords="82,298,117,300,116,318,97,319,94,336,83,333,83,333" href="https://kimeido.info/prefecture/41" alt="佐賀県" />
  <area shape="rect" coords="64,298,80,333" href="https://kimeido.info/prefecture/42" alt="長崎県" />
  <area shape="poly" coords="99,394,151,395,151,418,140,417,133,409,111,410,105,420,99,420,99,420" href="https://kimeido.info/prefecture/46" alt="鹿児島県" />
  <area shape="rect" coords="38,437,63,471" href="https://kimeido.info/prefecture/47" alt="沖縄県" />
</map>

app/views/search_parmacy/search_index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <% if @prefectures.present? %>
                <% @prefectures.each do |prefecture| %>
                <%= prefecture.name %>
                    <% prefecture.shops.each do |shop| %>
                        <%= shop.name %>
                    <% end %>
                <% end %>
            <% else %>
                <div class="card">
                    <h3 style="background: url('/top_images/todo_back.gif');">都道府県から探す</h3>
                    <div class="box">
                        <%= render partial: 'search_parmacy/map' %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-md-6">
            <div class="detail_search">
               <%= form_with url: search_pharmacy_path, scope: :search, method: :get, local: true, html: { class: 'detail_search'} do |f| %>
                   <div class="pref_search form-group">
                      <%= f.collection_select :prefecture, Prefecture.all, :id, :name %>
                   </div>
                   <!-- <%= f.submit '検索', class: 'btn btn-primary, btn-lg' %> -->
                <% end %>
            </div>
            
        </div>
    </div>
</div>
  