config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'tops/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tops#index'
  get '/prefecture/:id', to: 'tops#pref_index', as: :pref_index
  get 'show/:id', to: 'tops#show', as: :show
  get '/search', to: 'search_parmacy#search_index', as: :search_pharmacy
  get '/login' , to: 'sessions#new', as: :sign_in
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  namespace :shop do
    get "/new", to: "top#new"
    get "/dashboard/:id", to: "top#dashboard", as: :dashboard
    post "/create", to: "top#create", as: :create
    get "/des/:id", to: "shop_contents#des", as: :des
    post "/des/create", to: "shop_contents#create", as: :des_create
    get "des/edit/:id", to: "shop_contents#edit", as: :des_edit
    post "des/update/:id", to: "shop_contents#update", as: :des_update
    get "new/avatar", to: "shop_contents#avatar", as: :avatar
    post "create/avatar", to: "shop_contents#avatar_process", as: :avatar_process
  end

  namespace :admin do
    root to: "top#index"
    get "sign_up", to: "top#new", as: :new
    post "create", to: "top#create"
  end
end

app/views/layouts/_error_messages.html.erb
<% if @shop.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Place sticky footer content here.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
			<nav class="navbar navbar-default" id="header">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<%= link_to root_path do %>
							<%= image_tag '/top_images/e_logo_03.png', class: 'logologo', height: "50px" %>
						<% end %>
					</div>
					
					<div class="collapse navbar-collapse" id="navbarEexample">
						<% if logged_in_shop? %>
							<ul class="nav navbar-nav">
								<li><%= link_to 'ダッシュボード', shop_dashboard_path(current_shop) %></li>
								<li><%= link_to '店舗ページ', show_path(current_shop) %></li>
								<li><%= link_to 'ログアウト', logout_path, method: :delete, data: { confrim: '本当にログアウトしますか？' } %></li>
							</ul>
						<% else %>
						<ul class="nav navbar-nav">
							<li class="active"><%= link_to root_path do %>Home<% end %></li>
							<li><a href="#">About us</a></li>
							<li><a href="#">Contact</a></li>
						</ul>
						<% end %>
						<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
							<input type="text" class="form-control" placeholder="検索キーワード">
						</div>
						<button type="submit" class="btn btn-default">検索</button>
					</form>
					</div>
				</div>
			</nav>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>

  <body>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-rwdImageMaps/1.6/jquery.rwdImageMaps.min.js"></script>
    <%= render 'layouts/header' %>

      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
      
      
    <%= render partial: 'layouts/footer' %>
    

  </body>
</html>